[package]
name = "jasshaus-comm"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
serde = {version = "1.0", features = ["derive"] }

jasshaus-game = { path = "../game" }