[package]
name = "jasshaus-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread", "fs"] }

game-server = { path = "../../server" }
jasshaus-game = { path = "../game", features = ["server"] }