[package]
name = "tichu-server"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["macros", "sync", "rt-multi-thread", "fs"] }

tichu-game = { path = "../game", features = ["server"] }
game-server = { path = "../../server" }
